name: CMO Build Workflow

on:
  workflow_call:
    inputs:
      relno:
        type: string
        required: true
      branchName:   
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Print release number
        run: echo "Release is ${{ inputs.relno }}"
      - name: Get ACTION repo
        uses: actions/checkout@v3
        with:
          repository: Mani242003/CCBT_GLOBAL_DEVOPS_ACTION
          path: action-repo
      - name: Show all files
        run: ls -R
      - name: Checkout App Code
        run: |
          chmod +x action-repo/checkoutcode-mcmo.sh
          ./action-repo/checkoutcode-mcmo.sh "${{ inputs.branchName }}" "${{ secrets.GIT_TOKEN }}"
   


    
