name: CMO Build Workflow

on:
  workflow_call:
    inputs:
      relno:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Print release number
        run: echo "Release is ${{ inputs.relno }}"
       
      - name: List all files
        run: ls -R

   


    
