name: CMO Mobile - Build

on:
  workflow_call:
    inputs:
      relordev: { type: string, required: true }
      relno: { type: string, required: true }
      branchName: { type: string, required: true }
      buildimage: { type: string, required: true }
      uploadimage: { type: string, required: true }
      environment: { type: string, required: true }
      runner: { type: string, required: true }

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout App Code
        uses: actions/checkout@v4

      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: Mani242003/CCBT_GLOBAL_DEVOPS_ACTION
          path: scripts

      - name: Build JAR
        run: |
          chmod +x scripts/sh/buildjar-mcmo.sh
          scripts/sh/buildjar-mcmo.sh

      - name: Build & Push Docker Image
        run: |
          chmod +x scripts/sh/buildimage-mcmo.sh
          scripts/sh/buildimage-mcmo.sh ${{ inputs.relno }}
